version: '3'

services:
  php:
    container_name: ${APP_NAME:-conversional}-php
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/conversional
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
      - test_mysql
  nginx:
    container_name: ${APP_NAME:-conversional}-nginx
    image: nginx:latest
    ports:
      - ${HTTP_PORT:-8090}:80
    volumes:
      - ./:/conversional
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  mysql:
    container_name: ${APP_NAME:-conversional}-mysql
    image: mysql:5.7
    ports:
      - ${MYSQL_PORT:-9906}:3306
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
  test_mysql:
    container_name: ${APP_NAME:-conversional}-test-mysql
    image: mysql:5.7
    ports:
      - ${TEST_MYSQL_PORT:-9907}:3306
    volumes:
      - test_mysql_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}

volumes:
  mysql_data:
  test_mysql_data: